AllCops:
  TargetRubyVersion: 2.4.1
  Include:
    - '*.rb'
    - 'lib/**/*.rb'
    - 'spec/**/*.rb'
  Exclude:
    - '.**'
    - 'assets/**/*'
    - 'pages/**/*'
    - 'vendor/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
Metrics/BlockNesting:
  Exclude:
    - 'lib/magicbox/checks/*.rb'
Metrics/ClassLength:
  Exclude:
    - 'lib/magicbox/checks/*.rb'
Naming/FileName:
  Exclude:
    - Gemfile
    - Rakefile
Performance/RegexpMatch:
  Exclude:
    - 'magic.rb'
Style/RedundantReturn:
  Exclude:
    - 'lib/magicbox/checks/*.rb'

Lint/UriEscapeUnescape:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Security/Eval:
  Enabled: false
Style/BracesAroundHashParameters:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/RedundantBegin:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
#Consider for later
Style/SpecialGlobalVars:
  Enabled: false
#WHAT
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
