language: ruby
matrix:
  include:
  # 2017.3.1
  - rvm: 2.4.1
    env: PUPPET_VERSION=5.3.1
before_install:
  - yes | gem update --system --force
  - gem install bundler
  - bundle update --bundler
script:
  - 'bundle exec rubocop -D'
  - 'bundle exec rspec'
