---
webserver:
  host: 0.0.0.0
  port: 8443
  ssl_enable: true
  ssl_certificate: keys/magicbox.crt
  ssl_private_key: keys/magicbox.key

embedded_pages:
  - syntax/hello_world
  - syntax/querying_the_system
  - syntax/modifying_attributes
  - syntax/observe_your_change
  - syntax/validating_your_syntax
  - variables/putting_them_to_use
  - facts/what_are_they
  - facts/working_with_facts
  - facts/working_with_arrays
  - facts/working_with_hashes
  - facts/using_logic_with_facts
  - resources/exploring_package
  - resources/exploring_service
  - pfs/package_file
  - pfs/file_service
  - pfs/package_file_service

sample_pages:
  - index
  - validate
  - fact
  - function
  - resource
  - compile
  - apply
  - template
  - parser_validate
  - facts
  - factlogic
  - relationship

checks:
  validate:
    checks:
      - validate
  fact:
    checks:
      - validate
      - fact
    merge:
      lang: ruby
  function:
    checks:
      - validate
      - function
    merge:
      lang: ruby
  resource:
    checks:
      - resource
  compile:
    checks:
      - validate
      - compile
    merge:
      lang: puppet
  apply:
    checks:
      - validate
      - apply
    merge:
      lang: puppet
  template:
    checks:
      - validate
      - template
    merge:
      lang: erb
  facts:
    checks:
      - facts
  factlogic:
    checks:
      - validate
      - factlogic
    merge:
      lang: puppet
  relationship:
    checks:
      - validate
      - relationship
    merge:
      lang: puppet
